user www-data;
worker_processes 1;
pid /run/nginx.pid;

error_log /dev/stderr warn;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /dev/stdout;

    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;
    gzip on;

    fastcgi_buffers 8 16k;
    fastcgi_buffer_size 32k;

    include /etc/nginx/conf.d/*.conf;
}
