[program:varnish]
command=/usr/sbin/varnishd -F -a :80 -f /etc/varnish/default.vcl -s malloc,32m
autostart=false
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
